### PR TITLE
Updated to Naut 4.0

### PR DESCRIPTION
**Pull request by iPlain**
Updated the images and CSS file to Naut 4.0, along with bugfixes and
tweaks to match.

This update changes the style a decent amount, so don't be shocked.

I've tweaked the h5 header to work in this version, that's the one that
goes above the posts, but the h6 header wasn't working so it's commented
out.

Some color tweaks were added near the bottom, feel free to change those.

The 'footer' and 'sidebarimg' images are default, so they don't really
suit the sub, so they will need to be updated to something you choose.

RES-Nightmode support is included at the bottom, so you can add the text
'[](#/RES_SR_Config/NightModeCompatible)' somewhere in the sidebar text
to have it enabled by default.

You'll need to upload all the images that got updated in this PR for it to be compatible with the new CSS. 'headerbypass', 'logo', 'headercode', and 'flairsheet' are not used in the CSS as of right now.

I've got no idea how the auto updater and things are configed, so this probably breaks it ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by JulianNorton** [comment]
@purduekenny I was going to merge this but have it on a different branch until some of the default stock stuff is fixed, but I think having the annoying default images, and pushing this live, would encourage people to contribute. What do you think?

**Comment by purduekenny** [comment]
@JulianNorton if we followed it up with a stickied post about contributing I could see us getting some people who cared enough to contribute. i think it's necessary to communicate that though and not just assume it

**Comment by JulianNorton** [comment]
@purduekenny I'll merge it in now if you can write the sticky

**Comment by purduekenny** [comment]
Okay, I'll write the sticky :+1:

**Comment by purduekenny** [comment]
@JulianNorton the /r/testtheme does not look like what you've done to /r/web_design 

Looks like nightmode stuff is applying when night mode is not enabled.

**Pull request merged**
