### PR TITLE
Removed all placeholder related selectors

### PR DESCRIPTION
**Pull request by GasimGasimzada**

### CODE REVIEW

**Comment by JulianNorton** [comment]
> 2 additions, 1 deletion not shown because the diff is too large…

The changes are too large for me to effectively review. I understand most of the selectors are line 10, but I can't see the diff.

Can you add line breaks in one commit, show your changes, then in the next commit convert back to one line?

Once the specifics of the changes are clarified, I'll gladly merge the PR.

**Comment by GasimGasimzada** [comment]
What if I actually make that one line of uglified CSS to a more readable CSS? So, in the future we can make changes and not have issues like this?

**Comment by JulianNorton** [comment]
The reason why it's one line in the first place is because of reddit's limit on file size.

Uncompressed, it might be really close, or over reddit's limit of 100kb.

**Comment by GasimGasimzada** [comment]
Oh that makes sense! 

What if we use SASS and then compile all of them to a minified CSS? Can you set a script to run sass before uploading to reddit servers?

**Comment by JulianNorton** [comment]
I can just compile and manually minify it. Feel free to submit a new PR if you want to convert to SASS.

**Pull request closed without merging**
